server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/messenger_user_service
    username: user_service_app
    password: 12345
  main:
    allow-bean-definition-overriding: true

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: Pet-projects
  verification: /api/v1/cabinet/verification