spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true

app:
  jwt:
    secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
    issuer: Pet-projects
  verification: /api/v1/cabinet/verification



